package com.report.mapper.manage;

import com.report.common.pojo.SamplingTube;

import java.util.List;

public interface SamplingTubeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Wed May 02 17:28:25 CST 2018
     */
    int insert(SamplingTube record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Wed May 02 17:28:25 CST 2018
     */
    int insertSelective(SamplingTube record);

    //废除采样管
    int deleteTube(Integer id);

    List<SamplingTube> selectSamplingTubeByPaging(SamplingTube samplingTube);
    //查询用户采样管
    List<SamplingTube> selectSamplingTubeList(Integer userId);
}