package com.report.mapper.manage;

import com.report.common.pojo.UserType;

public interface UserTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_user_type
     *
     * @mbg.generated Wed May 02 17:07:20 CST 2018
     */
    int deleteByPrimaryKey(Integer userTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_user_type
     *
     * @mbg.generated Wed May 02 17:07:20 CST 2018
     */
    int insert(UserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_user_type
     *
     * @mbg.generated Wed May 02 17:07:20 CST 2018
     */
    int insertSelective(UserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_user_type
     *
     * @mbg.generated Wed May 02 17:07:20 CST 2018
     */
    UserType selectByPrimaryKey(Integer userTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_user_type
     *
     * @mbg.generated Wed May 02 17:07:20 CST 2018
     */
    int updateByPrimaryKeySelective(UserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_user_type
     *
     * @mbg.generated Wed May 02 17:07:20 CST 2018
     */
    int updateByPrimaryKey(UserType record);
}