package com.report.common.pojo;

import java.io.Serializable;

public class BacterialReport implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.bacterial_id
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Integer bacterialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.bacteroides_uniformis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double bacteroidesUniformis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.lactobacillus_salivarius
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double lactobacillusSalivarius;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.lactobacillus_acidophilus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double lactobacillusAcidophilus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.lactobacillus_fermentum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double lactobacillusFermentum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.streptococcus_thermophilus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double streptococcusThermophilus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.lactobacillus_helveticus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double lactobacillusHelveticus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.faecalibacterium_prausnitzii
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double faecalibacteriumPrausnitzii;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.lactobacillus_johnsonii
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double lactobacillusJohnsonii;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.lactobacillus_casei
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double lactobacillusCasei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.roseburia_inulinivorans
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double roseburiaInulinivorans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.lactococcus_lactis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double lactococcusLactis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.lactobacillus_reuteri
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double lactobacillusReuteri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.clostridium_butyricum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double clostridiumButyricum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.bifidobacterium_adolescentis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double bifidobacteriumAdolescentis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.bifidobacterium_bifidum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double bifidobacteriumBifidum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.bifidobacterium_angulatum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double bifidobacteriumAngulatum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.salmonella_enterica
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double salmonellaEnterica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.campylobacter_jejuni
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double campylobacterJejuni;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.clostridium_perfringens
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double clostridiumPerfringens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.klebsiella_pneumoniae
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double klebsiellaPneumoniae;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.bacteroides_fragilis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double bacteroidesFragilis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.enterobacter_aerogenes
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double enterobacterAerogenes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.bacteroides_stercoris
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double bacteroidesStercoris;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.escherichia_coli
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double escherichiaColi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.staphylococcus_aureus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double staphylococcusAureus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.enterococcus_faecium
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double enterococcusFaecium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.enterococcus_faecalis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double enterococcusFaecalis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.veillonella_parvula
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double veillonellaParvula;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.streptococcus_suis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double streptococcusSuis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.streptococcus_anginosus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double streptococcusAnginosus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_xcs_bacterial_report.fusobacterium_nucleatum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private Double fusobacteriumNucleatum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_xcs_bacterial_report
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.bacterial_id
     *
     * @return the value of t_xcs_bacterial_report.bacterial_id
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Integer getBacterialId() {
        return bacterialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.bacterial_id
     *
     * @param bacterialId the value for t_xcs_bacterial_report.bacterial_id
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setBacterialId(Integer bacterialId) {
        this.bacterialId = bacterialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.bacteroides_uniformis
     *
     * @return the value of t_xcs_bacterial_report.bacteroides_uniformis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getBacteroidesUniformis() {
        return bacteroidesUniformis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.bacteroides_uniformis
     *
     * @param bacteroidesUniformis the value for t_xcs_bacterial_report.bacteroides_uniformis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setBacteroidesUniformis(Double bacteroidesUniformis) {
        this.bacteroidesUniformis = bacteroidesUniformis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.lactobacillus_salivarius
     *
     * @return the value of t_xcs_bacterial_report.lactobacillus_salivarius
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getLactobacillusSalivarius() {
        return lactobacillusSalivarius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.lactobacillus_salivarius
     *
     * @param lactobacillusSalivarius the value for t_xcs_bacterial_report.lactobacillus_salivarius
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setLactobacillusSalivarius(Double lactobacillusSalivarius) {
        this.lactobacillusSalivarius = lactobacillusSalivarius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.lactobacillus_acidophilus
     *
     * @return the value of t_xcs_bacterial_report.lactobacillus_acidophilus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getLactobacillusAcidophilus() {
        return lactobacillusAcidophilus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.lactobacillus_acidophilus
     *
     * @param lactobacillusAcidophilus the value for t_xcs_bacterial_report.lactobacillus_acidophilus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setLactobacillusAcidophilus(Double lactobacillusAcidophilus) {
        this.lactobacillusAcidophilus = lactobacillusAcidophilus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.lactobacillus_fermentum
     *
     * @return the value of t_xcs_bacterial_report.lactobacillus_fermentum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getLactobacillusFermentum() {
        return lactobacillusFermentum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.lactobacillus_fermentum
     *
     * @param lactobacillusFermentum the value for t_xcs_bacterial_report.lactobacillus_fermentum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setLactobacillusFermentum(Double lactobacillusFermentum) {
        this.lactobacillusFermentum = lactobacillusFermentum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.streptococcus_thermophilus
     *
     * @return the value of t_xcs_bacterial_report.streptococcus_thermophilus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getStreptococcusThermophilus() {
        return streptococcusThermophilus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.streptococcus_thermophilus
     *
     * @param streptococcusThermophilus the value for t_xcs_bacterial_report.streptococcus_thermophilus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setStreptococcusThermophilus(Double streptococcusThermophilus) {
        this.streptococcusThermophilus = streptococcusThermophilus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.lactobacillus_helveticus
     *
     * @return the value of t_xcs_bacterial_report.lactobacillus_helveticus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getLactobacillusHelveticus() {
        return lactobacillusHelveticus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.lactobacillus_helveticus
     *
     * @param lactobacillusHelveticus the value for t_xcs_bacterial_report.lactobacillus_helveticus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setLactobacillusHelveticus(Double lactobacillusHelveticus) {
        this.lactobacillusHelveticus = lactobacillusHelveticus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.faecalibacterium_prausnitzii
     *
     * @return the value of t_xcs_bacterial_report.faecalibacterium_prausnitzii
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getFaecalibacteriumPrausnitzii() {
        return faecalibacteriumPrausnitzii;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.faecalibacterium_prausnitzii
     *
     * @param faecalibacteriumPrausnitzii the value for t_xcs_bacterial_report.faecalibacterium_prausnitzii
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setFaecalibacteriumPrausnitzii(Double faecalibacteriumPrausnitzii) {
        this.faecalibacteriumPrausnitzii = faecalibacteriumPrausnitzii;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.lactobacillus_johnsonii
     *
     * @return the value of t_xcs_bacterial_report.lactobacillus_johnsonii
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getLactobacillusJohnsonii() {
        return lactobacillusJohnsonii;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.lactobacillus_johnsonii
     *
     * @param lactobacillusJohnsonii the value for t_xcs_bacterial_report.lactobacillus_johnsonii
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setLactobacillusJohnsonii(Double lactobacillusJohnsonii) {
        this.lactobacillusJohnsonii = lactobacillusJohnsonii;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.lactobacillus_casei
     *
     * @return the value of t_xcs_bacterial_report.lactobacillus_casei
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getLactobacillusCasei() {
        return lactobacillusCasei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.lactobacillus_casei
     *
     * @param lactobacillusCasei the value for t_xcs_bacterial_report.lactobacillus_casei
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setLactobacillusCasei(Double lactobacillusCasei) {
        this.lactobacillusCasei = lactobacillusCasei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.roseburia_inulinivorans
     *
     * @return the value of t_xcs_bacterial_report.roseburia_inulinivorans
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getRoseburiaInulinivorans() {
        return roseburiaInulinivorans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.roseburia_inulinivorans
     *
     * @param roseburiaInulinivorans the value for t_xcs_bacterial_report.roseburia_inulinivorans
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setRoseburiaInulinivorans(Double roseburiaInulinivorans) {
        this.roseburiaInulinivorans = roseburiaInulinivorans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.lactococcus_lactis
     *
     * @return the value of t_xcs_bacterial_report.lactococcus_lactis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getLactococcusLactis() {
        return lactococcusLactis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.lactococcus_lactis
     *
     * @param lactococcusLactis the value for t_xcs_bacterial_report.lactococcus_lactis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setLactococcusLactis(Double lactococcusLactis) {
        this.lactococcusLactis = lactococcusLactis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.lactobacillus_reuteri
     *
     * @return the value of t_xcs_bacterial_report.lactobacillus_reuteri
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getLactobacillusReuteri() {
        return lactobacillusReuteri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.lactobacillus_reuteri
     *
     * @param lactobacillusReuteri the value for t_xcs_bacterial_report.lactobacillus_reuteri
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setLactobacillusReuteri(Double lactobacillusReuteri) {
        this.lactobacillusReuteri = lactobacillusReuteri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.clostridium_butyricum
     *
     * @return the value of t_xcs_bacterial_report.clostridium_butyricum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getClostridiumButyricum() {
        return clostridiumButyricum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.clostridium_butyricum
     *
     * @param clostridiumButyricum the value for t_xcs_bacterial_report.clostridium_butyricum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setClostridiumButyricum(Double clostridiumButyricum) {
        this.clostridiumButyricum = clostridiumButyricum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.bifidobacterium_adolescentis
     *
     * @return the value of t_xcs_bacterial_report.bifidobacterium_adolescentis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getBifidobacteriumAdolescentis() {
        return bifidobacteriumAdolescentis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.bifidobacterium_adolescentis
     *
     * @param bifidobacteriumAdolescentis the value for t_xcs_bacterial_report.bifidobacterium_adolescentis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setBifidobacteriumAdolescentis(Double bifidobacteriumAdolescentis) {
        this.bifidobacteriumAdolescentis = bifidobacteriumAdolescentis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.bifidobacterium_bifidum
     *
     * @return the value of t_xcs_bacterial_report.bifidobacterium_bifidum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getBifidobacteriumBifidum() {
        return bifidobacteriumBifidum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.bifidobacterium_bifidum
     *
     * @param bifidobacteriumBifidum the value for t_xcs_bacterial_report.bifidobacterium_bifidum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setBifidobacteriumBifidum(Double bifidobacteriumBifidum) {
        this.bifidobacteriumBifidum = bifidobacteriumBifidum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.bifidobacterium_angulatum
     *
     * @return the value of t_xcs_bacterial_report.bifidobacterium_angulatum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getBifidobacteriumAngulatum() {
        return bifidobacteriumAngulatum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.bifidobacterium_angulatum
     *
     * @param bifidobacteriumAngulatum the value for t_xcs_bacterial_report.bifidobacterium_angulatum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setBifidobacteriumAngulatum(Double bifidobacteriumAngulatum) {
        this.bifidobacteriumAngulatum = bifidobacteriumAngulatum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.salmonella_enterica
     *
     * @return the value of t_xcs_bacterial_report.salmonella_enterica
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getSalmonellaEnterica() {
        return salmonellaEnterica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.salmonella_enterica
     *
     * @param salmonellaEnterica the value for t_xcs_bacterial_report.salmonella_enterica
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setSalmonellaEnterica(Double salmonellaEnterica) {
        this.salmonellaEnterica = salmonellaEnterica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.campylobacter_jejuni
     *
     * @return the value of t_xcs_bacterial_report.campylobacter_jejuni
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getCampylobacterJejuni() {
        return campylobacterJejuni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.campylobacter_jejuni
     *
     * @param campylobacterJejuni the value for t_xcs_bacterial_report.campylobacter_jejuni
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setCampylobacterJejuni(Double campylobacterJejuni) {
        this.campylobacterJejuni = campylobacterJejuni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.clostridium_perfringens
     *
     * @return the value of t_xcs_bacterial_report.clostridium_perfringens
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getClostridiumPerfringens() {
        return clostridiumPerfringens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.clostridium_perfringens
     *
     * @param clostridiumPerfringens the value for t_xcs_bacterial_report.clostridium_perfringens
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setClostridiumPerfringens(Double clostridiumPerfringens) {
        this.clostridiumPerfringens = clostridiumPerfringens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.klebsiella_pneumoniae
     *
     * @return the value of t_xcs_bacterial_report.klebsiella_pneumoniae
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getKlebsiellaPneumoniae() {
        return klebsiellaPneumoniae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.klebsiella_pneumoniae
     *
     * @param klebsiellaPneumoniae the value for t_xcs_bacterial_report.klebsiella_pneumoniae
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setKlebsiellaPneumoniae(Double klebsiellaPneumoniae) {
        this.klebsiellaPneumoniae = klebsiellaPneumoniae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.bacteroides_fragilis
     *
     * @return the value of t_xcs_bacterial_report.bacteroides_fragilis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getBacteroidesFragilis() {
        return bacteroidesFragilis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.bacteroides_fragilis
     *
     * @param bacteroidesFragilis the value for t_xcs_bacterial_report.bacteroides_fragilis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setBacteroidesFragilis(Double bacteroidesFragilis) {
        this.bacteroidesFragilis = bacteroidesFragilis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.enterobacter_aerogenes
     *
     * @return the value of t_xcs_bacterial_report.enterobacter_aerogenes
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getEnterobacterAerogenes() {
        return enterobacterAerogenes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.enterobacter_aerogenes
     *
     * @param enterobacterAerogenes the value for t_xcs_bacterial_report.enterobacter_aerogenes
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setEnterobacterAerogenes(Double enterobacterAerogenes) {
        this.enterobacterAerogenes = enterobacterAerogenes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.bacteroides_stercoris
     *
     * @return the value of t_xcs_bacterial_report.bacteroides_stercoris
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getBacteroidesStercoris() {
        return bacteroidesStercoris;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.bacteroides_stercoris
     *
     * @param bacteroidesStercoris the value for t_xcs_bacterial_report.bacteroides_stercoris
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setBacteroidesStercoris(Double bacteroidesStercoris) {
        this.bacteroidesStercoris = bacteroidesStercoris;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.escherichia_coli
     *
     * @return the value of t_xcs_bacterial_report.escherichia_coli
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getEscherichiaColi() {
        return escherichiaColi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.escherichia_coli
     *
     * @param escherichiaColi the value for t_xcs_bacterial_report.escherichia_coli
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setEscherichiaColi(Double escherichiaColi) {
        this.escherichiaColi = escherichiaColi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.staphylococcus_aureus
     *
     * @return the value of t_xcs_bacterial_report.staphylococcus_aureus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getStaphylococcusAureus() {
        return staphylococcusAureus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.staphylococcus_aureus
     *
     * @param staphylococcusAureus the value for t_xcs_bacterial_report.staphylococcus_aureus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setStaphylococcusAureus(Double staphylococcusAureus) {
        this.staphylococcusAureus = staphylococcusAureus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.enterococcus_faecium
     *
     * @return the value of t_xcs_bacterial_report.enterococcus_faecium
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getEnterococcusFaecium() {
        return enterococcusFaecium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.enterococcus_faecium
     *
     * @param enterococcusFaecium the value for t_xcs_bacterial_report.enterococcus_faecium
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setEnterococcusFaecium(Double enterococcusFaecium) {
        this.enterococcusFaecium = enterococcusFaecium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.enterococcus_faecalis
     *
     * @return the value of t_xcs_bacterial_report.enterococcus_faecalis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getEnterococcusFaecalis() {
        return enterococcusFaecalis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.enterococcus_faecalis
     *
     * @param enterococcusFaecalis the value for t_xcs_bacterial_report.enterococcus_faecalis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setEnterococcusFaecalis(Double enterococcusFaecalis) {
        this.enterococcusFaecalis = enterococcusFaecalis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.veillonella_parvula
     *
     * @return the value of t_xcs_bacterial_report.veillonella_parvula
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getVeillonellaParvula() {
        return veillonellaParvula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.veillonella_parvula
     *
     * @param veillonellaParvula the value for t_xcs_bacterial_report.veillonella_parvula
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setVeillonellaParvula(Double veillonellaParvula) {
        this.veillonellaParvula = veillonellaParvula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.streptococcus_suis
     *
     * @return the value of t_xcs_bacterial_report.streptococcus_suis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getStreptococcusSuis() {
        return streptococcusSuis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.streptococcus_suis
     *
     * @param streptococcusSuis the value for t_xcs_bacterial_report.streptococcus_suis
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setStreptococcusSuis(Double streptococcusSuis) {
        this.streptococcusSuis = streptococcusSuis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.streptococcus_anginosus
     *
     * @return the value of t_xcs_bacterial_report.streptococcus_anginosus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getStreptococcusAnginosus() {
        return streptococcusAnginosus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.streptococcus_anginosus
     *
     * @param streptococcusAnginosus the value for t_xcs_bacterial_report.streptococcus_anginosus
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setStreptococcusAnginosus(Double streptococcusAnginosus) {
        this.streptococcusAnginosus = streptococcusAnginosus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_xcs_bacterial_report.fusobacterium_nucleatum
     *
     * @return the value of t_xcs_bacterial_report.fusobacterium_nucleatum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public Double getFusobacteriumNucleatum() {
        return fusobacteriumNucleatum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_xcs_bacterial_report.fusobacterium_nucleatum
     *
     * @param fusobacteriumNucleatum the value for t_xcs_bacterial_report.fusobacterium_nucleatum
     *
     * @mbg.generated Wed May 02 17:08:36 CST 2018
     */
    public void setFusobacteriumNucleatum(Double fusobacteriumNucleatum) {
        this.fusobacteriumNucleatum = fusobacteriumNucleatum;
    }
}