package com.report.common.pojo;

import java.util.ArrayList;
import java.util.List;

public class SamplingTubeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    public SamplingTubeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTubeNumberIsNull() {
            addCriterion("tube_number is null");
            return (Criteria) this;
        }

        public Criteria andTubeNumberIsNotNull() {
            addCriterion("tube_number is not null");
            return (Criteria) this;
        }

        public Criteria andTubeNumberEqualTo(String value) {
            addCriterion("tube_number =", value, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeNumberNotEqualTo(String value) {
            addCriterion("tube_number <>", value, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeNumberGreaterThan(String value) {
            addCriterion("tube_number >", value, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeNumberGreaterThanOrEqualTo(String value) {
            addCriterion("tube_number >=", value, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeNumberLessThan(String value) {
            addCriterion("tube_number <", value, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeNumberLessThanOrEqualTo(String value) {
            addCriterion("tube_number <=", value, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeNumberLike(String value) {
            addCriterion("tube_number like", value, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeNumberNotLike(String value) {
            addCriterion("tube_number not like", value, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeNumberIn(List<String> values) {
            addCriterion("tube_number in", values, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeNumberNotIn(List<String> values) {
            addCriterion("tube_number not in", values, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeNumberBetween(String value1, String value2) {
            addCriterion("tube_number between", value1, value2, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeNumberNotBetween(String value1, String value2) {
            addCriterion("tube_number not between", value1, value2, "tubeNumber");
            return (Criteria) this;
        }

        public Criteria andTubeBindingIsNull() {
            addCriterion("tube_binding is null");
            return (Criteria) this;
        }

        public Criteria andTubeBindingIsNotNull() {
            addCriterion("tube_binding is not null");
            return (Criteria) this;
        }

        public Criteria andTubeBindingEqualTo(Integer value) {
            addCriterion("tube_binding =", value, "tubeBinding");
            return (Criteria) this;
        }

        public Criteria andTubeBindingNotEqualTo(Integer value) {
            addCriterion("tube_binding <>", value, "tubeBinding");
            return (Criteria) this;
        }

        public Criteria andTubeBindingGreaterThan(Integer value) {
            addCriterion("tube_binding >", value, "tubeBinding");
            return (Criteria) this;
        }

        public Criteria andTubeBindingGreaterThanOrEqualTo(Integer value) {
            addCriterion("tube_binding >=", value, "tubeBinding");
            return (Criteria) this;
        }

        public Criteria andTubeBindingLessThan(Integer value) {
            addCriterion("tube_binding <", value, "tubeBinding");
            return (Criteria) this;
        }

        public Criteria andTubeBindingLessThanOrEqualTo(Integer value) {
            addCriterion("tube_binding <=", value, "tubeBinding");
            return (Criteria) this;
        }

        public Criteria andTubeBindingIn(List<Integer> values) {
            addCriterion("tube_binding in", values, "tubeBinding");
            return (Criteria) this;
        }

        public Criteria andTubeBindingNotIn(List<Integer> values) {
            addCriterion("tube_binding not in", values, "tubeBinding");
            return (Criteria) this;
        }

        public Criteria andTubeBindingBetween(Integer value1, Integer value2) {
            addCriterion("tube_binding between", value1, value2, "tubeBinding");
            return (Criteria) this;
        }

        public Criteria andTubeBindingNotBetween(Integer value1, Integer value2) {
            addCriterion("tube_binding not between", value1, value2, "tubeBinding");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdIsNull() {
            addCriterion("tube_user_id is null");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdIsNotNull() {
            addCriterion("tube_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdEqualTo(Integer value) {
            addCriterion("tube_user_id =", value, "tubeUserId");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdNotEqualTo(Integer value) {
            addCriterion("tube_user_id <>", value, "tubeUserId");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdGreaterThan(Integer value) {
            addCriterion("tube_user_id >", value, "tubeUserId");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tube_user_id >=", value, "tubeUserId");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdLessThan(Integer value) {
            addCriterion("tube_user_id <", value, "tubeUserId");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("tube_user_id <=", value, "tubeUserId");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdIn(List<Integer> values) {
            addCriterion("tube_user_id in", values, "tubeUserId");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdNotIn(List<Integer> values) {
            addCriterion("tube_user_id not in", values, "tubeUserId");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdBetween(Integer value1, Integer value2) {
            addCriterion("tube_user_id between", value1, value2, "tubeUserId");
            return (Criteria) this;
        }

        public Criteria andTubeUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tube_user_id not between", value1, value2, "tubeUserId");
            return (Criteria) this;
        }

        public Criteria andTubeStateIsNull() {
            addCriterion("tube_state is null");
            return (Criteria) this;
        }

        public Criteria andTubeStateIsNotNull() {
            addCriterion("tube_state is not null");
            return (Criteria) this;
        }

        public Criteria andTubeStateEqualTo(Integer value) {
            addCriterion("tube_state =", value, "tubeState");
            return (Criteria) this;
        }

        public Criteria andTubeStateNotEqualTo(Integer value) {
            addCriterion("tube_state <>", value, "tubeState");
            return (Criteria) this;
        }

        public Criteria andTubeStateGreaterThan(Integer value) {
            addCriterion("tube_state >", value, "tubeState");
            return (Criteria) this;
        }

        public Criteria andTubeStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("tube_state >=", value, "tubeState");
            return (Criteria) this;
        }

        public Criteria andTubeStateLessThan(Integer value) {
            addCriterion("tube_state <", value, "tubeState");
            return (Criteria) this;
        }

        public Criteria andTubeStateLessThanOrEqualTo(Integer value) {
            addCriterion("tube_state <=", value, "tubeState");
            return (Criteria) this;
        }

        public Criteria andTubeStateIn(List<Integer> values) {
            addCriterion("tube_state in", values, "tubeState");
            return (Criteria) this;
        }

        public Criteria andTubeStateNotIn(List<Integer> values) {
            addCriterion("tube_state not in", values, "tubeState");
            return (Criteria) this;
        }

        public Criteria andTubeStateBetween(Integer value1, Integer value2) {
            addCriterion("tube_state between", value1, value2, "tubeState");
            return (Criteria) this;
        }

        public Criteria andTubeStateNotBetween(Integer value1, Integer value2) {
            addCriterion("tube_state not between", value1, value2, "tubeState");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeIsNull() {
            addCriterion("creater_time is null");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeIsNotNull() {
            addCriterion("creater_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeEqualTo(Integer value) {
            addCriterion("creater_time =", value, "createrTime");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeNotEqualTo(Integer value) {
            addCriterion("creater_time <>", value, "createrTime");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeGreaterThan(Integer value) {
            addCriterion("creater_time >", value, "createrTime");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("creater_time >=", value, "createrTime");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeLessThan(Integer value) {
            addCriterion("creater_time <", value, "createrTime");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeLessThanOrEqualTo(Integer value) {
            addCriterion("creater_time <=", value, "createrTime");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeIn(List<Integer> values) {
            addCriterion("creater_time in", values, "createrTime");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeNotIn(List<Integer> values) {
            addCriterion("creater_time not in", values, "createrTime");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeBetween(Integer value1, Integer value2) {
            addCriterion("creater_time between", value1, value2, "createrTime");
            return (Criteria) this;
        }

        public Criteria andCreaterTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("creater_time not between", value1, value2, "createrTime");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdIsNull() {
            addCriterion("tube_report_id is null");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdIsNotNull() {
            addCriterion("tube_report_id is not null");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdEqualTo(Integer value) {
            addCriterion("tube_report_id =", value, "tubeReportId");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdNotEqualTo(Integer value) {
            addCriterion("tube_report_id <>", value, "tubeReportId");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdGreaterThan(Integer value) {
            addCriterion("tube_report_id >", value, "tubeReportId");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tube_report_id >=", value, "tubeReportId");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdLessThan(Integer value) {
            addCriterion("tube_report_id <", value, "tubeReportId");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdLessThanOrEqualTo(Integer value) {
            addCriterion("tube_report_id <=", value, "tubeReportId");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdIn(List<Integer> values) {
            addCriterion("tube_report_id in", values, "tubeReportId");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdNotIn(List<Integer> values) {
            addCriterion("tube_report_id not in", values, "tubeReportId");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdBetween(Integer value1, Integer value2) {
            addCriterion("tube_report_id between", value1, value2, "tubeReportId");
            return (Criteria) this;
        }

        public Criteria andTubeReportIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tube_report_id not between", value1, value2, "tubeReportId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated do_not_delete_during_merge Fri May 04 10:41:15 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_xcs_sampling_tube
     *
     * @mbg.generated Fri May 04 10:41:15 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}